### PR TITLE
res/: add Clear Linux icon

### PR DESCRIPTION
**Pull request by wight554**
Packages can be found here https://github.com/wight554/ClearWSL/

### CODE REVIEW

**Comment by yuk7** [comment]
Ok!

**Comment by yuk7** [comment]
I'm sorry I'm late.
Created a new release that includes this commit.

**Comment by wight554** [comment]
Tnx for release but is it possible to create one with Clear.exe?

**Comment by yuk7** [comment]
Oops,sorry!
Pushed [19083100](https://github.com/yuk7/wsldl/releases/tag/19083100) release now

**Pull request merged**
